// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvcfntuwyhgfbbdruihq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2Y2ZudHV3eWhnZmJiZHJ1aWhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTE3MjAsImV4cCI6MjA2ODc2NzcyMH0.1-4IKPHvkYJ3QO5Tjia2tVT6gqTyp96uVxP-GiyMntg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});